language: python
python:
  - "3.9"
install:
- pip install -r requirements.txt 
env: 
 - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/tagr
 - AWS_ACCESS_KEY_ID=testing
 - AWS_SECRET_ACCESS_KEY=testing
 - AWS_SECURITY_TOKEN=testing
 - AWS_SESSION_TOKEN=testing
script:
 - python -m unittest discover test/
cache: pip
