language: python
python:
  - "3.9"
install:
- pip install -r requirements.txt 
- pip install coverage
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/tagr
    - AWS_ACCESS_KEY_ID=testing
    - AWS_SECRET_ACCESS_KEY=testing
    - AWS_SECURITY_TOKEN=testing
    - AWS_SESSION_TOKEN=testing
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run -m unittest discover test/
after_script:
  - coverage xml
  - export CC_TEST_REPORTER_ID=73ca08d2c04e22855420f1c4606e83bfaab2535c47c5e394e4fbe6fa361a9564
  - ./cc-test-reporter format-coverage -t coverage.py
  - ./cc-test-reporter upload-coverage
  - ./cc-test-reporter after-build --exit-code $?
cache: pip
