language: python
python:
  - "3.9"
install:
- pip install -r requirements-dev.txt 
- pip install coverage
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/tagr
    - AWS_ACCESS_KEY_ID=testing
    - AWS_SECRET_ACCESS_KEY=testing
    - AWS_SECURITY_TOKEN=testing
    - AWS_SESSION_TOKEN=testing
    - GOOGLE_APPLICATION_CREDENTIALS=testing
    - AZURE_STORAGE_ACCOUNT=testing
    - AZURE_STORAGE_KEY=testing

script:
  - coverage run -m unittest discover test/
  - black --check .
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: pip
